config/routes.rb
NorthwindApp::Application.routes.draw do

  root 'odata#index'
  resources :odata
  get '/supplier', :to => 'odata#supplier'
  post '/supplier', :to => 'odata#supplier'
  get 'orders', :to => 'odata#orders'
  post 'orders', :to => 'odata#orders'
  get 'contacts', :to => 'odata#contacts'
  post 'contacts', :to => 'odata#contacts'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/odata_controller.rb
class OdataController < ApplicationController
	# Standard HTTP Request
	require "net/http"
	require "uri"
	# Needed to use the json library
	require "rubygems" 
	require "json"


	def index
	end

	def supplier
		# Get the productID input by the user in the supplier form
		@productID = params[:productID]
		# Initialize the flag
		@received = false
		# Set the urls needed
		@productsURL = "Products?$format=json"
		@suppliersURL = "Suppliers?$format=json"
		# Create a display service document to parse a url and get the value array
		# of the products & Suppliers table
		productsDoc = DisplayServiceDocument.new
		productValues = productsDoc.parseURL(@productsURL)
		suppliersDoc = DisplayServiceDocument.new
		suppliersValues = suppliersDoc.parseURL(@suppliersURL)
		# Product ID part
		productName = productsDoc.getItem(productValues, "ProductID", @productID, "ProductName") 
		# Suppliers ID part
		supplierID = productsDoc.getItem(productValues, "ProductID", @productID, "SupplierID") 
		# Active/Discontinued part
		active = productsDoc.getItem(productValues, "ProductID", @productID, "Discontinued")
		if active 
			active = "Discontinued"
		else 
			active = "Active"
		end
		# Supplier name -- Use in this case the suppliers table
		companyName = suppliersDoc.getItem(suppliersValues, "SupplierID", supplierID, "CompanyName") 			
		@output = {"companyName" => companyName, "productName" => productName, 
					"supplierID" => supplierID, "active" => active, "companyName" => companyName }
		# Activate the flag when a product ID is received			
		if @productID != nil
			@received = true
		end
	end

	def orders
		#Get the productID input by the user in the supplier form
		productID = params[:productID]
		# Initialize the flag
		@received = false
		# Set the urls needed
		@productsURL = "Products?$format=json"
		@orderDetailsURL = "Order_Details?$format=json"

		# Create a display service document to parse a url and get the value array
		# of the products & orders table
		productsDoc = DisplayServiceDocument.new
		productValues = productsDoc.parseURL(@productsURL)
		orderDetailsDoc = DisplayServiceDocument.new
		orderDetailsValues = orderDetailsDoc.parseURL(@orderDetailsURL)
		# Product ID part
		productName = productsDoc.getItem(productValues, "ProductID", productID, "ProductName") 
		# Orders part
		count = 0
		@output = {"productID"=>productID}
		order = Hash.new
		orderDetailsValues.each do |item|
			if item["ProductID"].to_i == productID.to_i
				totalPrice = item["UnitPrice"].to_i*item["Quantity"].to_i*(1-item["Discount"].to_i)
				count += 1
				order[item["OrderID"].to_s] = totalPrice 
				puts order
			end
		end
		@output["count"] = count
		@output["order"] = order
		puts @output
		# Activate the flag when a product ID is received			
		if productID != nil
			@received = true
		end
	end

	def contacts
		#Get the productID input by the user in the supplier form
		productID = params[:productID]
		# Initialize the flag
		@received = false
		# Set the urls needed
		@productsURL = "Products?$format=json"
		@orderDetailsURL = "Order_Details?$format=json"
		@ordersURL = "Orders?$format=json"
		@customersURL = "Customers?$format=json"

		# Create a display service document to parse a url and get the value array
		# of the tables required
		aDoc = DisplayServiceDocument.new
		productValues = aDoc.parseURL(@productsURL)
		orderDetailsValues = aDoc.parseURL(@orderDetailsURL)
		ordersValues = aDoc.parseURL(@ordersURL)
		customersValues = aDoc.parseURL(@customersURL)

		# Orders part
		# Count the number or orders for that product ID
		count = 0
		names = Array.new
		# Get the contact name info for each order
		orderDetailsValues.each do |item|
			if item["ProductID"].to_i == productID.to_i
				count += 1
				ordersValues.each do |order|
					if order["OrderID"].to_i == item["OrderID"].to_i
						customersValues.each do |customer|
							if customer["CustomerID"] == order["CustomerID"]
								if customer["ContactName"].empty? == false
									puts customer["ContactName"]
									names.push(customer["ContactName"])
								end
							end
						end
					end
				end
			end
		end
		@output = {"productID" => productID, "count" => count, "names" => names}
		puts @output
		# Activate the flag when a product ID is received			
		if productID != nil
			@received = true
		end
	end
end

class DisplayServiceDocument
	# Standard HTTP Request
	require "net/http"
	require "uri"
	# Needed to use the json library
	require "rubygems" 
	require "json"
	
	
	# Method to parse a url and return the value array
	def parseURL(table)
		northwind = "http://services.odata.org/northwind/northwind.svc/"
		# Parse the url address
		uri = URI.parse(northwind+table)

		# Will get response.body
		response = Net::HTTP.get(uri)
		# Parse the response
		parsedResponse = JSON.parse(response)
		# Get the value array from the JSON response
		values = parsedResponse["value"]
	end
	# Method to get a specific attribute
	def getItem(array, matchItem, matchValue, returnValue)
		#puts "matchItem " + matchItem
		#puts "matchValue" + matchValue
		#puts "returnValue" + returnValue
		name = ""
		array.each do |item|
			if item[matchItem].to_i == matchValue.to_i
				name = item[returnValue]
				#puts name
			end
		end
		#puts name
		return name.to_s
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/odata_helper.rb
module OdataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NorthwindApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css"%>
  <%= javascript_include_tag "http://code.jquery.com/jquery-1.8.2.min.js" %>
  <%= javascript_include_tag "http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js" %> 
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div id="navig" class="container-fluid">
    <ul class="nav nav-pills">
    <div class="col-xs-4 slogan">
      	<%= link_to 'NorthWind App', root_path %>
    </div>
    	<li role="presentation"><%= link_to 'Find Supplier', supplier_path %></li>
    	<li role="presentation"><%= link_to 'List Orders', orders_path %></li>
    	<li role="presentation"><%= link_to 'Contact Names', contacts_path %></li>
    </ul>
  </div>
</nav>
<hr />
<br class="clear" />
<div id="myBody" class="container">
	<%= yield %>
</div>


</body>
</html>

app/views/odata/contacts.html.erb
<div class="col-md-5 col-xs-12">
  <div class="container">
  	<h1>Contact Names</h1>
  	<%= bootstrap_form_tag :action => 'orders' do |f| %>
		<%= f.search_field :productID, hide_label: true, placeholder: 'Type the Product ID' %>
		<%= f.submit "Search" %>
		<div class="jumbotron">
			<h2><%= result = "Product Summary:" if @received %></h2>
			<p><%= result = "Product ID = #{@output['productID']}" if @received %></p>
			<p><%= result = "The number of orders for product ID #{@output['productID']} is #{@output['count']}" if @received %></p>
			<table class="table table-hover">
				<tr>
					<th><%= result = "Contact Name" if @received %></th>
				</tr>
				<% 	@output["names"].each { |contact|
						idCell = contact 
				%>
				<tr>
					<td><%= idCell %></td>	
				</tr>
				<% } %>
			</table>
		</div>
  	<% end %>
  </div>
</div>

app/views/odata/index.html.erb
<div id="jumbo">
	<div class="jumbotron">
		<div class="container">
			<h1> Welcome to NorthWind App</h1>
			<p>Please select the desired functionality from the navigation bar above</p>
		</div>
	</div>
</div>
<div id="description" class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="jumbotron">
				<h4>Find Supplier</h4>
				<p>Enter a product ID to find information about that product's supplier</p>
			</div>
		</div>
		<div class="col-md-4">
			<div class="jumbotron">
				<h4>List Orders</h4>
				<p>Given a product ID get the list order IDs and their total price after discount</p>
			</div>
		</div>
		<div class="col-md-4">
			<div class="jumbotron">
				<h4>Contact Names</h4>
				<p>Given a product ID get the list of contact names for each order</p>
			</div>
		</div>
	</div>
</div>

app/views/odata/orders.html.erb
<div class="col-md-5 col-xs-12 ">
  <div class="container">
  	<h1>List Orders</h1>
  	<%= bootstrap_form_tag :action => 'orders' do |f| %>
		<%= f.search_field :productID, hide_label: true, placeholder: 'Type the Product ID' %>
		<%= f.submit "Search" %>
		<div class="jumbotron">
			<h2><%= result = "Product Summary:" if @received %></h2>
			<p><%= result = "Product ID = #{@output['productID']}" if @received %></p>
			<p><%= result = "The number of orders for product ID #{@output['productID']} is #{@output['count']}" if @received %></p>
			<table class="table table-hover">
				<tr>
					<th><%= result = "Order ID" if @received %></th>
					<th><%= result = "Total" if @received %></th>
				</tr>
				<% @output["order"].each do |orderid,total|
					idCell = orderid
					totalCell = total %>
				<tr>
					<td><%= idCell %></td>	
					<td><%= totalCell %></td>
				</tr>
				<% end %>
			</table>
		</div>
  	<% end %>
  </div>
</div>

app/views/odata/supplier.html.erb
<div class="col-md-5 col-xs-12">
  <div class="container">
  	<h1>Find the supplier</h1>
  	<%= bootstrap_form_tag :action => 'supplier' do |f| %>
		<%= f.search_field :productID, hide_label: true, placeholder: 'Type the Product ID' %>
		<%= f.submit "Search" %>
		<div class="jumbotron">
			<h2><%= result = "Product Summary:" if @received %></h2>
			<p><%= result = "Product ID = #{@productID}" if @received %></p>
			<p><%= result = "Product name = #{@output['productName']}" if @received %></p>
			<p><%= result = "Supplier ID = #{@output['supplierID']}" if @received %></p>
			<p><%= result = "#{@output['productName']} is a #{@output['active']} product" if @received %></p>
			<br></br>
			<h2><%= result = "Supplier name" if @received %></h2>
			<p><%= result = "#{@output['companyName']}" if @received %></p>
		</div>
  	<% end %>
  </div>
</div>